[window]
dynamic_padding = true
decorations = "Full"
decorations_theme_variant = "Dark"

[window.padding]
x = 6
y = 0

[font]
size = 15.0

[font.normal]
family = "MesloLGS NF"

[keyboard]
bindings = [
    { key = "Left",     mods = "Alt",     chars = "\u001bb"                           },
    { key = "Right",    mods = "Alt",     chars = "\u001bf"                           },
    { key = "Left",     mods = "Command", chars = "\u001bOH",   mode = "AppCursor"    },
    { key = "Right",    mods = "Command", chars = "\u001bOF",   mode = "AppCursor"    },
    { key = "Back",     mods = "Command", chars = "\u0015"                            },
]

[colors.primary]
background = "#000000"
foreground = "#fffbf6"

[colors.normal]
black   = "#2e2e2e"
red     = "#eb4129"
green   = "#abe047"
yellow  = "#f6c744"
blue    = "#47a0f3"
magenta = "#7b5cb0"
cyan    = "#64dbed"
white   = "#e5e9f0"

[colors.bright]
black   = "#565656"
red     = "#ec5357"
green   = "#c0e17d"
yellow  = "#f9da6a"
blue    = "#49a4f8"
magenta = "#a47de9"
cyan    = "#99faf2"
white   = "#ffffff"
